export const SIGN_UP = "SIGN_UP"
export const SIGN_IN = "SIGN_IN"
export const GOOGLE_SIGN_IN = "GOOGLE_SIGN_IN"
export const SIGNED_IN = "SIGNED_IN"
export const LOG_OUT = "LOG_OUT"
export const LOGGED_OUT = "LOGGED_OUT"
export const FORGATE_PASSWORD = "FORGATE_PASSWORD"
export const FORGATED_PASSWORD = "FORGATED_PASSWORD"

export const SET_ALERT = "SET_ALERT"
export const RESET_ALERT = "RESET_ALERT"